### PR TITLE
Release 0.4.0

### PR DESCRIPTION
**Pull request by paul-mannino**
Preparing a 0.4.0 release, as requested in https://github.com/zargony/fuse-rs/issues/147. Built & tested examples on Ubuntu 18.04.

Let me know if there's any work I missed.

### CODE REVIEW

**Comment by paul-mannino** [comment]
failing in CI for freebsd, but the way the error message reads, it seems like it's not related to the pull or the state of the codebase. Looks like it might be CI config related & has been failing for a while now.

**Comment by delehef** [comment]
> failing in CI for freebsd, but the way the error message reads, it seems like it's not related to the pull or the state of the codebase. Looks like it might be CI config related & has been failing for a while now.

Hi,

I just tested it for confirmation on a clean FreeBSD 12.0-RELEASE VM I have, and it builds, runs and tests perfectly. The error in the CI looks like it stems from a misconfiguration of FreeBSD's `pkg`.

Thanks for your work!

**Comment by zargony** [comment]
Thanks for your help. Actually I was expecting to release 0.4.0 based on the 0.3.0 branch since changes in master are pretty much under development, a lot of things are in a flux and I don't think it's ready for a release yet (E.g. there's two different Filesystem traits, a lot of duplicate types because of the introduced `lowlevel` module). It's supposed to be cleaned up once #126 is ready, but this isn't the case yet.

**Comment by zargony** [comment]
@delehef do you think it's a misconfiguration on Cirrus CI's side or on our side? Unfortunately I'm not so familiar with the FreeBSD package system. Do you have an idea how this could be fixed?

**Comment by delehef** [comment]
> @delehef do you think it's a misconfiguration on Cirrus CI's side or on our side? Unfortunately I'm not so familiar with the FreeBSD package system. Do you have an idea how this could be fixed?

Definitely looks like their `pkg` (FreeBSD's package manager) configuration is borked, I don't see how it could be on our side.

> Do you have an idea how this could be fixed?

Could Cirrus be setup to use a more recent FreeBSD release?

**Comment by delehef** [comment]
Looks like `tokio` met the same problem, and [updating to FreeBSD 12.1](https://github.com/tokio-rs/tokio/pull/2403/files) fixed it!

**Comment by zargony** [comment]
> Looks like tokio met the same problem, and updating to FreeBSD 12.1 fixed it!

Thanks! Should be fixed with #149

**Comment by paul-mannino** [comment]
@zargony I realize I forgot to ping you on this, but I prepared something that is hopefully closer to what you were looking for. I cherry-picked/backported changes off master that were related to bug fixes or removing that deprecated time dependency. Left this up as a PR even though obviously this wouldn't be merged.

**Comment by oxalica** [comment]
Any update here? I'm also waiting for 0.4.0

**Comment by theduke** [comment]
@zargony friendly ping, also waiting for this.

**Comment by theduke** [comment]
FYI: there is an actively maintained fork of this project here: https://github.com/cberner/fuser

**Pull request closed without merging**
