### PR TITLE
added friendlier build messages closes #54

### LINKED ISSUE #54: Add details about dependencies (install instructions) to README
I am trying to build this from the repo on Ubuntu 15.04 and having some trouble, I was hoping that you could point me in the right direction. I have fuse installed `fuse is already the newest version.` but there seems to be something in the build script that is triggering a build failure. I tracked it down to the fact that the program below has the output that it does. But I have fuse installed, so I'm not sure where to go from here.

```
$ pkg-config --libs --cflags libfuse
Package libfuse was not found in the pkg-config search path.
Perhaps you should add the directory containing `libfuse.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libfuse' found
```

For now, I commented out the build script in `Cargo.toml` and it builds just fine. I'm not sure how to proceed from here but just wanted to let you know that I ran into this problem on my machine.

### PR DESCRIPTION
**Pull request by waynenilsen**
This confused me for a few minutes mostly because i had `fuse` installed but not `libfuse-dev` this should be a more helpful message to people with this problem.

### CODE REVIEW

**Comment by cuviper** [comment]
Linux is not just Ubuntu.  On Fedora the package is `fuse-devel`, for instance.  This block also covers BSD.

It already knows whether you're on osx or something else, at least, so it doesn't need to offer suggestions for both.

**Comment by waynenilsen** [comment]
Your comments make sense. Before I change the code some more, I want to make sure you'll be happy with the changes. I made some line comments, let me know what you think.

**Comment by frabrunelle** [comment]
On OS X I knew I had to install `osxfuse` but on Ubuntu 15.10 I was confused for a few minutes.

I ended searching the issues on this repo and I was able to figure out that I had to install `libfuse-dev`.

:+1: for having a more helpful message!

**Comment by zargony** [comment]
I just played around with build.rs and found that lib probing can be greatly simplified since OSXFUSE also provides `fuse.pc`. This way, we can use `probe_library("fuse")` on any platform.

I don't think we should give OS-specific instructions how to install FUSE in build.rs. Ubuntu and Fedora might be common, but there are so many Linux distributions and package names are not standardized. Maybe we should add some more detailed instructions to `README.md` though.

**Pull request closed without merging**
